<?php
include("conn.php");

// Function to generate code
function generateCode($conn) {
    $sql = "SELECT MAX(code) as max_serial_no FROM codes_lakowe";
    $result = mysqli_query($conn, $sql);
    $row = mysqli_fetch_assoc($result);
    $next_serial_no = $row['max_serial_no'] + 1;
    $code = sprintf("%03d", $next_serial_no);
    return $code;
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Check if a code has already been generated by this session today
    $today = date("Y-m-d");
    if (isset($_SESSION['code_generated_today']) && $_SESSION['code_generated_today'] == $today) {
        echo "<script>alert('You have already generated a code today. Please try again tomorrow.'); window.location.href='../';</script>";
        exit();
    }

    // Set session variable to mark today's code generation
    $_SESSION['code_generated_today'] = $today;

    // Get user info from session
    $email = $_SESSION['email']; // Assuming email is stored in session
    // Fetch user name from database using email
    $sql = "SELECT firstName, lastName FROM users WHERE email='$email'";
    $result = mysqli_query($conn, $sql);
    if ($row = mysqli_fetch_assoc($result)) {
        $name = $row['firstName'] . ' ' . $row['lastName'];
    } else {
        echo "<script>alert('User not found.'); window.location.href='../';</script>";
        exit();
    }

    // Generate code
    $code = generateCode($conn);
    $date_time = date("Y-m-d H:i:s");

    // Insert new code into database
    $sql = "INSERT INTO codes_lakowe (serial_no, name, code, date_time) VALUES (NULL, '$name', '$code', '$date_time')";
    if (mysqli_query($conn, $sql)) {
        echo "<script>alert('Code generated successfully: $code!'); window.location.href='../';</script>";
        exit();
    } else {
        echo "<script>alert('Error: " . $sql . "<br>" . mysqli_error($conn) . "'); window.location.href='../';</script>";
        exit();
    }
}

// Fetch user list from database
$sql = "SELECT * FROM codes_lakowe";
$result = mysqli_query($conn, $sql);
$user_list_from_generate_php = [];
if (mysqli_num_rows($result) > 0) {
    while ($row = mysqli_fetch_assoc($result)) {
        $user_list_from_generate_php[] = $row;
    }
}

// Close connection
mysqli_close($conn);
?>